version: '3'
services:
 # Node.js Service
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Node.js Dockerfile
    depends_on:
      - mongo
      - redis
    restart: always
    environment: # MOCK DATA
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=bot_token
      - MONGO_URI=mongodb://username:password@mongo:27017/db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"  # Adjust the port as needed
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    networks:
      - bot
  # MongoDB Service
  mongo:
    image: "mongo:latest"
    restart: always
    environment: # MOCK DATA
      MONGO_INITDB_DATABASE: dbname
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongodb:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - "27017:27017"  # Expose MongoDB port if needed
    networks:
      - bot
  # Redis Service
  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"  # Expose Redis port if needed
    networks:
      - bot
volumes: {}
networks:
  bot:
